# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    set PATH=C:\Miniconda3;C:\Miniconda3\Scripts;%PATH%
    set PYTHONPATH=C:\projects\solar_test
    cmd: conda config --set always_yes yes --set changeps1 no
    cmd: conda info -a
    cmd: conda env create -f environment.yml
  displayName: 'Install System Environment'

- script: echo %PYTHON_VERSION%
  displayName: 'Python'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
